export type Niche = { name: string; category: string; people: string };
export const CATEGORIES = [
  "Technology",
  "Design",
  "Film",
  "Stories",
  "Build",
  "Science",
  "Business",
  "Culture",
  "Impact",
  "Music",
];
export const CREATOR_ROLES = [
  "Creator",
  "Builder",
  "Designer",
  "Filmmaker",
  "Writer",
  "Researcher",
  "Founder",
  "Explorer",
];
export const NICHES: Niche[] = [
  ["Songwriting", "Music", "songwriters"],
  ["Live Performance", "Music", "performers"],
  ["Audio Mixing", "Music", "mix engineers"],
  ["Instrumental Music", "Music", "musicians"],
  ["Music Education", "Music", "music educators"],
  ["Film Scores", "Music", "composers"],
  ["Poetry", "Stories", "poets"],
  ["Spoken Word", "Stories", "spoken-word creators"],
  ["Book Reviews", "Stories", "book creators"],
  ["Creative Nonfiction", "Stories", "essayists"],
  ["Typography", "Design", "type designers"],
  ["Brand Identity", "Design", "brand designers"],
  ["Fashion Styling", "Culture", "style creators"],
  ["Food Storytelling", "Culture", "food creators"],
  ["Astronomy", "Science", "space enthusiasts"],
  ["Nature Education", "Impact", "nature educators"],
  ["Language Learning", "Culture", "language creators"],
  ["Comics", "Design", "comic artists"],
  ["Artificial Intelligence", "Technology", "AI builders"],
  ["Computer Vision", "Technology", "visual engineers"],
  ["Robotics", "Technology", "robot makers"],
  ["Machine Learning", "Technology", "ML creators"],
  ["Cybersecurity", "Technology", "security builders"],
  ["Creative Coding", "Technology", "creative technologists"],
  ["Product Design", "Design", "product designers"],
  ["UI/UX Design", "Design", "experience designers"],
  ["3D Design", "Design", "3D artists"],
  ["Illustration", "Design", "illustrators"],
  ["Animation", "Film", "animators"],
  ["Filmmaking", "Film", "filmmakers"],
  ["Motion Design", "Film", "motion designers"],
  ["Documentary", "Film", "documentary creators"],
  ["Storytelling", "Stories", "storytellers"],
  ["Writing", "Stories", "writers"],
  ["Music Production", "Music", "music producers"],
  ["Product Building", "Build", "product builders"],
  ["Startups", "Build", "early-stage founders"],
  ["Hardware", "Build", "hardware makers"],
  ["Open Source", "Build", "open-source contributors"],
  ["Game Development", "Build", "game creators"],
  ["Medical Imaging", "Science", "health-tech researchers"],
  ["Space Technology", "Science", "space builders"],
  ["Climate Science", "Science", "climate creators"],
  ["Neuroscience", "Science", "brain researchers"],
  ["Biotechnology", "Science", "bio-tech builders"],
  ["Human–AI Interaction", "Science", "HCI researchers"],
  ["3D Gaussian Splatting", "Technology", "spatial AI creators"],
  ["Generative Vision", "Technology", "generative artists"],
  ["Autonomous Vehicles", "Technology", "autonomy engineers"],
  ["Visual Robotics", "Technology", "vision-robotics builders"],
  ["No-Code Tools", "Build", "no-code makers"],
  ["Mobile Apps", "Build", "app creators"],
  ["Web Development", "Build", "web builders"],
  ["Indie Hacking", "Build", "indie founders"],
  ["Creator Economy", "Business", "creator strategists"],
  ["Brand Strategy", "Business", "brand builders"],
  ["Digital Marketing", "Business", "growth creators"],
  ["Community Building", "Business", "community leaders"],
  ["Social Entrepreneurship", "Business", "impact founders"],
  ["E-commerce", "Business", "commerce creators"],
  ["Photography", "Film", "photographers"],
  ["Cinematography", "Film", "cinematographers"],
  ["Video Editing", "Film", "video editors"],
  ["Sound Design", "Music", "sound designers"],
  ["Podcasting", "Stories", "podcasters"],
  ["Screenwriting", "Stories", "screenwriters"],
  ["Journalism", "Stories", "journalists"],
  ["Worldbuilding", "Stories", "worldbuilders"],
  ["Fashion Design", "Culture", "fashion creators"],
  ["Architecture", "Culture", "architectural creators"],
  ["Digital Art", "Culture", "digital artists"],
  ["Education", "Impact", "learning creators"],
  ["Accessibility", "Impact", "inclusive designers"],
  ["Sustainability", "Impact", "sustainability creators"],
  ["Civic Technology", "Impact", "civic-tech builders"],
  ["Mental Health Advocacy", "Impact", "wellbeing advocates"],
].map(([name, category, people]) => ({ name, category, people }));
