import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { colors, radius, spacing } from '@/constants/theme';

const creators=[
 {name:'Maya',role:'3D artist + animator',score:91,shared:'AI · Storytelling',edge:'Your computer vision + Maya’s animation could become an interactive character.'},
 {name:'Arun',role:'Hardware maker',score:86,shared:'Robotics · Open Source',edge:'You share robotics, while Arun adds prototyping and hardware experience.'},
 {name:'Noor',role:'Filmmaker + designer',score:82,shared:'Film · Design',edge:'A complementary match for visual storytelling and creative technology projects.'}
];
export default function Discover(){return <SafeAreaView style={styles.page}><View style={styles.header}><View><Text style={styles.kicker}>DISCOVER</Text><Text style={styles.title}>People worth knowing.</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>TS</Text></View></View><Text style={styles.body}>Ranked by creative compatibility — never follower count.</Text><ScrollView contentContainerStyle={styles.list}>{creators.map((c,i)=><View key={c.name} style={styles.card}><View style={styles.row}><View style={styles.person}><Text style={styles.number}>0{i+1}</Text><View><Text style={styles.name}>{c.name}</Text><Text style={styles.role}>{c.role}</Text></View></View><Text style={styles.score}>{c.score}%</Text></View><Text style={styles.shared}>{c.shared}</Text><View style={styles.why}><Text style={styles.whyLabel}>WHY THIS MATCH</Text><Text style={styles.whyText}>{c.edge}</Text></View><TouchableOpacity style={styles.action}><Text style={styles.actionText}>Explore connection →</Text></TouchableOpacity></View>)}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background,padding:spacing.lg},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:spacing.sm},kicker:{color:colors.signal,fontSize:11,fontWeight:'900',letterSpacing:1.8},title:{color:colors.text,fontSize:30,fontWeight:'900',letterSpacing:-.8,marginTop:4},avatar:{width:42,height:42,borderRadius:21,backgroundColor:colors.surfaceRaised,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.signal,fontWeight:'900'},body:{color:colors.muted,marginTop:spacing.sm,marginBottom:spacing.md},list:{gap:14,paddingBottom:30},card:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,padding:spacing.lg},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},person:{flexDirection:'row',gap:12,alignItems:'center'},number:{color:colors.muted,fontSize:11,fontWeight:'900'},name:{color:colors.text,fontSize:22,fontWeight:'900'},role:{color:colors.muted,fontSize:12,marginTop:2},score:{color:colors.signal,fontSize:24,fontWeight:'900'},shared:{color:colors.signalSoft,fontWeight:'800',marginTop:spacing.lg},why:{borderTopWidth:1,borderColor:colors.border,marginTop:spacing.md,paddingTop:spacing.md},whyLabel:{color:colors.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.5},whyText:{color:colors.text,lineHeight:21,marginTop:6},action:{marginTop:spacing.md},actionText:{color:colors.signal,fontWeight:'900'}});
