import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { colors, radius, spacing } from '@/constants/theme';

export default function DnaScreen(){
 const {interests=''}=useLocalSearchParams<{interests:string}>(); const items=interests.split(',').filter(Boolean).slice(0,6);
 return <SafeAreaView style={styles.page}><Text style={styles.step}>YOUR SIGNAL</Text><Text style={styles.title}>This is your{`\n`}Interest DNA.</Text><Text style={styles.body}>Not a personality test. A living map of what you're curious about and where your creative network can grow.</Text>
 <View style={styles.map}><View style={styles.core}><Text style={styles.coreText}>YOU</Text></View>{items.map((x,i)=><View key={x} style={[styles.item,{transform:[{rotate:`${(i-2)*4}deg`}]}]}><View style={styles.dot}/><Text style={styles.label}>{x}</Text></View>)}</View>
 <View style={styles.insight}><Text style={styles.insightLabel}>SIGNAL INSIGHT</Text><Text style={styles.insightText}>Your strongest matches won't always look like you. TrueSignal also looks for creators whose skills can extend your interests.</Text></View>
 <TouchableOpacity style={styles.button} onPress={()=>router.push('/discover')}><Text style={styles.buttonText}>Find my people</Text></TouchableOpacity></SafeAreaView>
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background,padding:spacing.lg},step:{color:colors.signal,fontSize:11,fontWeight:'900',letterSpacing:1.8,marginTop:spacing.md},title:{color:colors.text,fontSize:40,lineHeight:44,fontWeight:'900',letterSpacing:-1.2,marginTop:spacing.md},body:{color:colors.muted,fontSize:15,lineHeight:23,marginTop:spacing.sm},map:{flex:1,justifyContent:'center',gap:9,paddingVertical:spacing.lg},core:{alignSelf:'center',width:76,height:76,borderRadius:38,backgroundColor:colors.signal,alignItems:'center',justifyContent:'center',marginBottom:10},coreText:{fontWeight:'900',color:'#090A0F'},item:{flexDirection:'row',alignItems:'center',gap:12,alignSelf:'center',minWidth:220,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,padding:13,borderRadius:radius.pill},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.violet},label:{color:colors.text,fontWeight:'800'},insight:{backgroundColor:colors.surfaceRaised,borderRadius:radius.md,padding:spacing.md,marginBottom:spacing.md},insightLabel:{color:colors.cyan,fontSize:10,fontWeight:'900',letterSpacing:1.5},insightText:{color:colors.text,lineHeight:21,marginTop:7,fontWeight:'600'},button:{backgroundColor:colors.signal,padding:18,borderRadius:radius.md,alignItems:'center'},buttonText:{color:'#090A0F',fontWeight:'900',fontSize:16}});
